language: node_js
node_js:
- '6'
script: NODE_ENV=test mocha test/index_tests
deploy:
  provider: heroku
  app: prima-mocha-tester
  api_key:
    secure: ZSMemQS1UWW2hQKUOf4ro4bDrvfOVDkZYrVPH7JSngwdj2bvtVbCXQ4AnGaEijYk8xfb/VoFNtlennKnFkj2YOu4paCkWDXBLzXJF5w7QHcwnQatU5n3V5qdHFt88QGwk0+OmFT+0qB0FuSnCAz2v4sa18B05Nk1REWqgJpO4uQFnVWuIiwN94w9H0AL9vAn2lBvoh5u99bO7S8Ka0J/m4K6XrGUdioB92WWs2M0mh1y4G5CXsHeJGqxU62QNoHKbzPL/sz+a/Gm09f82DFci9RAHOK6QDldqsw6lqu4tXkGSgm+h3rSi7yJpNk8CNWnhy/MZove5uCqUBpkKjCS4PHQxuhsl0CWSYJVT836iQ/x2sMGOvVDFa8BDM2tZrYcTYiVG8nFSDO9f4K2bBroS8f0YwynziWm1EFzCJG+DTLS2kNKwYra8BX/lLad1wg0a45104emfmjplKjlaZw3EsXzcQ7cq3m8W+JtlisRV+7Ix6FS1FLCR0oR4pYyu9q630OrV5I8z1k2rJ8iwuZ+f69NwpqydVQnxEp5Ass4U11Bxmg/y0QueHBY5RH30m3uCGcvEi5kfJT1QILYJkW+MuCpARyFvK/X7oWrwkyu5BtZVuSwEqh33FB0duDbSslB2nh4kj23Xu4hc+K7O/BLmO3lmb5oM+PoQXsp6eGPHsk=
